// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void anno_time_left_Animation( lv_obj_t *TargetObject, int delay);
void anno_se_dance_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Main1
void ui_Main1_screen_init(void);
void ui_event_Main1( lv_event_t * e);
extern lv_obj_t *ui_Main1;
extern lv_obj_t *ui_tempInfo;
extern lv_obj_t *ui_tempLabP;
extern lv_obj_t *ui_tempVal;
extern lv_obj_t *ui_humidityInfo;
extern lv_obj_t *ui_humidityP;
extern lv_obj_t *ui_humidityVal;
extern lv_obj_t *ui_homeTime;
extern lv_obj_t *ui_hour;
extern lv_obj_t *ui_se1;
extern lv_obj_t *ui_min;
extern lv_obj_t *ui_se2;
extern lv_obj_t *ui_sec;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_water_baoyu_png);   // assets/water/baoyu.png

LV_FONT_DECLARE( ui_font_HEITI21);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
